name: .NET Core CI

on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/Dockerfile'
      - '**/docker-image.yml'
      
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '**/Dockerfile'
      - '**/docker-image.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/OSISDiscordAssistant.sln
    - name: Build
      run: dotnet build ./src/OSISDiscordAssistant.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test ./src/OSISDiscordAssistant.sln --no-build --verbosity detailed
